### ISSUE TITLE
Unable to run contrail-api-cli on Contrail 3.0

### ISSUE THREAD

**Issue by saad-ngnware** [eonpatapon/contrail-api-cli#16]
I'm facing the following error. '' TypeError: register_argparse_arguments() got an unexpected keyword argument 'default' '' when I run the following command in shell: contrail-api-cli  or any argument it keeps throwing the same error. 
Been stuck at this for hours now. Any help would be great.

**Comment by eonpatapon** [comment]
Please paste the full traceback.

**Comment by saad-ngnware** [comment]
`Traceback (most recent call last):
  File "/usr/bin/contrail-api-cli", line 9, in <module>
    load_entry_point('contrail-api-cli==0.1b2', 'console_scripts', 'contrail-api-cli')()
  File "/usr/lib/python2.7/dist-packages/contrail_api_cli/main.py", line 57, in main
    auth.register_argparse_arguments(parser, argv, default="http")
TypeError: register_argparse_arguments() got an unexpected keyword argument 'default'`

The above is the stack trace no matter what arguments I pass to contrail-api-cli

**Comment by eonpatapon** [comment]
What's your python-keystoneclient version ?

**Comment by saad-ngnware** [comment]
python-keystoneclient 0.10.1

**Comment by eonpatapon** [comment]
I think it is too old can you try with a newer version ?

**Comment by eonpatapon** [comment]
You need 0.11.0 at least. I will update the requirements

**Comment by saad-ngnware** [comment]
Okay Thanks! I'll test it and let you know if any success comes my way.

**Comment by eonpatapon** [comment]
Does it work ?

**Comment by saad-ngnware** [comment]
Yes it did after a lot of tries. https://pypi.python.org/pypi/contrail-api-cli
I compiled your code using the above link because pip wasn't getting me anywhere and I was running into all sorts of issues. But the thing here is that there seems to be no 'tree' command which is what I was looking forward to. Can you guide me what could be the possible issue?
My keystone version is 1.20 and Contrail 3.02 with Openstack Kilo 
![image](https://cloud.githubusercontent.com/assets/16112846/16521586/4e0d3bc2-3fb1-11e6-878f-3af0531333c6.png)

**Comment by eonpatapon** [comment]
Here is a sample installation : https://asciinema.org/a/a6m3mrpgc9rte8bf7gdzhdxst

**Comment by saad-ngnware** [comment]
I have been running into this same error on all Contrail 3.0 distros.
![image](https://cloud.githubusercontent.com/assets/16112846/16522215/c17b0504-3fb5-11e6-868a-e2aa74cb9ef3.png)

**Comment by saad-ngnware** [comment]
Unfortunately I have been running into this error on all Contrail 3.0 distros.
![image](https://cloud.githubusercontent.com/assets/16112846/16522238/f7071352-3fb5-11e6-97fc-7ba3c19b2bb7.png)

**Comment by eonpatapon** [comment]
I don't get it, can you paste the pip.log somewhere maybe ?

**Comment by saad-ngnware** [comment]
Downloading/unpacking contrail-api-cli
  Getting page https://pypi.python.org/simple/contrail-api-cli/
  URLs to search for versions for contrail-api-cli:
  * https://pypi.python.org/simple/contrail-api-cli/
  Analyzing links from page https://pypi.python.org/simple/contrail-api-cli/
    Found link https://pypi.python.org/packages/3e/ba/545153e4a794c66f7382daf6702035a55636d6821c615c8364f73b0b3f94/contrail-api-cli-0.1rc2.tar.gz#md5=993848155b7edfed35b799cc71ec312e (from https://pypi.python.org/simple/contrail-api-cli/), version: 0.1rc2
    Found link https://pypi.python.org/packages/81/d9/c640bfbdff1e52845c2cbe5f07450516bff135241427ad8db92a5bbd8b43/contrail-api-cli-0.1b2.tar.gz#md5=ddbda48283ab9235b4915e59be0cac91 (from https://pypi.python.org/simple/contrail-api-cli/), version: 0.1b2
    Found link https://pypi.python.org/packages/b2/e2/bd3ffe38399b8c1764861204621fa7ba0b912c8c7cfc6a92321daa9d6fa7/contrail-api-cli-0.1a3.tar.gz#md5=1816261cefa4acc616d78e3ea6d860b6 (from https://pypi.python.org/simple/contrail-api-cli/), version: 0.1a3
    Found link https://pypi.python.org/packages/e4/84/b6761fbd8535da9c9791590df45ceb43c78c1d135a7213963b77838b88f4/contrail-api-cli-0.1a1.tar.gz#md5=4bc145b6eb0e5c62caa7cdd156095916 (from https://pypi.python.org/simple/contrail-api-cli/), version: 0.1a1
    Found link https://pypi.python.org/packages/ed/0e/165c6e696ad4f131c2508b7f189443e55d86b02e71d6442cc6b3aacd9674/contrail-api-cli-0.1b1.tar.gz#md5=9b521662ffc43ab5eb8bae1f2036fec3 (from https://pypi.python.org/simple/contrail-api-cli/), version: 0.1b1
    Found link https://pypi.python.org/packages/f8/a2/0d55e3970731c9a5643abf135c1c8fe6c984e0f39e35c8e100aa3af529ea/contrail-api-cli-0.1a2.tar.gz#md5=073a3e2e9bbbb9b73401f6b32261fde0 (from https://pypi.python.org/simple/contrail-api-cli/), version: 0.1a2
  Ignoring link https://pypi.python.org/packages/3e/ba/545153e4a794c66f7382daf6702035a55636d6821c615c8364f73b0b3f94/contrail-api-cli-0.1rc2.tar.gz#md5=993848155b7edfed35b799cc71ec312e (from https://pypi.python.org/simple/contrail-api-cli/), version 0.1rc2 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/81/d9/c640bfbdff1e52845c2cbe5f07450516bff135241427ad8db92a5bbd8b43/contrail-api-cli-0.1b2.tar.gz#md5=ddbda48283ab9235b4915e59be0cac91 (from https://pypi.python.org/simple/contrail-api-cli/), version 0.1b2 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/b2/e2/bd3ffe38399b8c1764861204621fa7ba0b912c8c7cfc6a92321daa9d6fa7/contrail-api-cli-0.1a3.tar.gz#md5=1816261cefa4acc616d78e3ea6d860b6 (from https://pypi.python.org/simple/contrail-api-cli/), version 0.1a3 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/e4/84/b6761fbd8535da9c9791590df45ceb43c78c1d135a7213963b77838b88f4/contrail-api-cli-0.1a1.tar.gz#md5=4bc145b6eb0e5c62caa7cdd156095916 (from https://pypi.python.org/simple/contrail-api-cli/), version 0.1a1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/ed/0e/165c6e696ad4f131c2508b7f189443e55d86b02e71d6442cc6b3aacd9674/contrail-api-cli-0.1b1.tar.gz#md5=9b521662ffc43ab5eb8bae1f2036fec3 (from https://pypi.python.org/simple/contrail-api-cli/), version 0.1b1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/f8/a2/0d55e3970731c9a5643abf135c1c8fe6c984e0f39e35c8e100aa3af529ea/contrail-api-cli-0.1a2.tar.gz#md5=073a3e2e9bbbb9b73401f6b32261fde0 (from https://pypi.python.org/simple/contrail-api-cli/), version 0.1a2 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement contrail-api-cli (from versions: 0.1rc2, 0.1b2, 0.1a3, 0.1a1, 0.1b1, 0.1a2)
Cleaning up...
  Removing temporary dir /root/cli/build...
No distributions matching the version for contrail-api-cli
Exception information:
Traceback (most recent call last):
  File "/root/cli/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/root/cli/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/root/cli/local/lib/python2.7/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/root/cli/local/lib/python2.7/site-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for contrail-api-cli

**Comment by eonpatapon** [comment]
Seems you need to run `pip install --pre contrail-api-cli`
