### ISSUE TITLE
Correct AS number is not reflected in the BGP peer after BGP peer router addition using contrail-api-cli

### ISSUE THREAD

**Issue by sureshkvl** [eonpatapon/contrail-api-cli#17]
Issue :   
Given BGP AS number for the BGP Peer is not updated properly.

When i add the BGP peer using  contrail CLI, the BGP Peer AS number is modified to the local AS number instead of the given one.

1)

/usr/bin/contrail-api-cli --ns contrail_api_cli.provision add-bgp-router  --router-ip 192.168.122.230  --router-asn  64510  mitaka6

Here  mitaka6 AS Number is 64510.

2)

⌂119% 2d [cloud@mitak5:~/devstack] stable/mitaka* ± /usr/bin/contrail-api-cli --ns contrail_api_cli.provision list-bgp-router
[
  {
    "router_port": 179,
    "router_asn": 64513,
    "router_md5": [],
    "router_ip": "192.168.122.185",
    "router_address_families": [
      "route-target",
      "inet-vpn",
      "e-vpn",
      "erm-vpn",
      "inet6-vpn"
    ],
    "router_type": "contrail",
    "router_name": "mitak5"
  },
  {
    "router_port": 179,
    "router_asn": 64513,
    "router_md5": [],
    "router_ip": "192.168.122.230",
    "router_address_families": [
      "route-target",
      "inet-vpn",
      "e-vpn",
      "erm-vpn",
      "inet6-vpn"
    ],
    "router_type": "contrail",
    "router_name": "mitaka6"
  }
]

In this, it has been modified as 64513 (local AS number)

The log show, after the CREATE bgp router,
UPDATE is called with 64513 AS number.
Attached the log for reference.

4. To resolve this issue, I have edited this object(using Contrail api cli)  and updated the AS number.

**Comment by nlewo** [comment]
This issue has to be reported in the contrail-api-cli-extra repo since the code is not (yet) in the contrail-api-cli repository.
