### ISSUE TITLE
Installation Error on CentOS

### ISSUE THREAD

**Issue by ssmolsky** [eonpatapon/contrail-api-cli#24]
Hello:   I'm not sure this is the correct forum to raise an issue regarding installation errors

When following the install instructions on a CentOS machine, I get the following errors.   

...
Download error on https://pypi.python.org/simple/pbr/: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:579) -- Some packages may not be found!
...
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=2.0.0')
...

Can anybody provide guidance?     
Also, does this require a specific version of Python?   My environment is defaulting to python 2.7.

**Comment by eonpatapon** [comment]
You seem to have an issue contacting pypi.
Do you have some proxy maybe ?

**Comment by ssmolsky** [comment]
Thanks for the response.   Proxy issue resolved.
